unbind C-b
set-option -g prefix C-Space

set-option -g mouse

if-shell "test -f ~/.config/tmux/tmux.line.conf" "source ~/.config/tmux/tmux.line.conf"

bind r source-file ~/.config/tmux/tmux.conf
bind-key C-Space resize-pane -Z

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

set-option -g focus-events on
set -g default-terminal "xterm-256color"
set-option -sa terminal-overrides ',*:RGB'
set-option -sg escape-time 10
set-option -g renumber-windows on

set -g @batt_remain_short 'true'

set -g history-limit 10000
# Use vim keybindings in copy mode
setw -g mode-keys vi

# Setup 'v' to begin selection as in Vim
bind-key -Tcopy-mode-vi 'v' send -X begin-selection
bind-key -Tcopy-mode-vi Escape send -X cancel
bind-key -Tcopy-mode-vi V send -X rectangle-toggle

set -s set-clipboard external

# Set new panes to open in current directory
# bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g @tmux_window_name_shells "['zsh', 'bash', 'sh']"
set -g @tmux_window_dir_programs "['nvim', 'vim', 'vi', 'git', 'node', 'npm']"
set -g @tmux_window_name_use_tilde "True"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'ofirgall/tmux-window-name'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'MunifTanjim/tmux-mode-indicator'
set -g @plugin 'tmux-plugins/tmux-battery'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
